src/Pool/LinkmotorBundle/Entity/Domain.php
<?php

namespace Pool\LinkmotorBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Pool\LinkmotorBundle\Entity\Project;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Domain
 *
 * @ORM\Table(name="domains")
 * @ORM\Entity(repositoryClass="Pool\LinkmotorBundle\Entity\DomainRepository")
 * @UniqueEntity(fields={"name"}, message="This domain is already taken!")
 */
class Domain
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="name", type="string", length=128)
     * @Assert\NotBlank()
     * @Assert\Regex(
     *     pattern="/[\/:]/",
     *     match=false,
     *     message="The domain may not contain / or :"
     * )
     */
    protected $name;

    /**
     * @ORM\Column(name="authority", type="integer")
     */
    protected $authority;

    /**
     * @ORM\Column(name="link_pop", type="integer", nullable=true)
     */
    protected $linkPop;

    /**
     * @ORM\Column(name="domain_pop", type="integer", nullable=true)
     */
    protected $domainPop;

    /**
     * @ORM\Column(name="net_pop", type="integer", nullable=true)
     */
    protected $netPop;

    /**
     * @var \DateTime
     * @ORM\Column(name="first_day", type="date", nullable=true)
     */
    protected $firstDay;

    /**
     * @ORM\Column(name="last_crawled_at", type="datetime", nullable=true)
     */
    protected $lastCrawledAt;

    /**
     * @ORM\OneToMany(targetEntity="Subdomain", mappedBy="domain")
     * @ORM\OrderBy({"name" = "ASC"})
     */
    protected $subdomains;

    /**
     * @ORM\OneToMany(targetEntity="Blacklist", mappedBy="domain")
     */
    protected $blacklists;

    /**
     * @ORM\OneToMany(targetEntity="Competitor", mappedBy="domain")
     */
    protected $competitors;

    /**
     * @ORM\ManyToOne(targetEntity="Vendor", inversedBy="domains")
     * @ORM\JoinColumn(name="vendor_id", referencedColumnName="id")
     */
    protected $vendor;

    /**
     * @ORM\OneToMany(targetEntity="Project", mappedBy="domain")
     */
    protected $projects;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->setAuthority(0);
        $this->setDomainPop(null);
        $this->setLinkPop(null);
        $this->setNetPop(null);
        $this->setName('');
        $this->subdomains = new \Doctrine\Common\Collections\ArrayCollection();
        $this->blacklists = new \Doctrine\Common\Collections\ArrayCollection();
        $this->competitors = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * @param string $url
     *
     * @return bool
     */
    public function urlMatches($url)
    {
        // Issue #70: Prüfung der Domain funktioniert bei // als Protokoll nicht
        // Das scheint ein PHP-Bug zu sein, der auf dem Server noch nicht behoben ist.
        // Deshalb hier ein Workaround.

        $emptyScheme = false;
        if (strpos($url, '//') === 0) {
            $url = 'http:' . $url;
            $emptyScheme = true;
        }
        $urlParts = $this->getUrlParts($url);
        if ($emptyScheme) {
            $urlParts['scheme'] = '';
        }

        return $urlParts['domain'] == $this->getName();
    }

    /**
     * @todo wird auch in PageCreator und Subdomain benutzt
     * @param string $url
     * @return array
     */
    public function getUrlParts($url)
    {
        $urlParts = parse_url($url);

        if (!isset($urlParts['path'])) {
            $path = '/';
        } else {
            $path = $urlParts['path'];
        }

        if (isset($urlParts['query'])) {
            $path .= '?' . $urlParts['query'];
        }

        $urlParts['host'] = isset($urlParts['host']) ? $urlParts['host'] : '';
        $urlParts['host'] = strtolower($urlParts['host']);
        $parts = explode('.', $urlParts['host']);
        if (count($parts) == 2) {
            $domain = $urlParts['host'];
            $subdomain = '';
        } else {
            $subdomain = array_shift($parts);
            $domain = implode('.', $parts);
        }

        return array(
            'scheme' => isset($urlParts['scheme']) ? $urlParts['scheme'] : '',
            'domain' => $domain,
            'subdomain' => $subdomain,
            'path' => $path
        );
    }

    public function getNumPages(Project $project)
    {
        $numPages = 0;

        foreach ($this->getSubdomains() as $subdomain) {
            foreach ($subdomain->getPages() as $page) {
                if ($page->getProject() == $project) {
                    $numPages++;
                }
            }
        }

        return $numPages;
    }

    public function getNumBacklinks(Project $project)
    {
        $numBacklinks = 0;

        foreach ($this->getSubdomains() as $subdomain) {
            foreach ($subdomain->getPages() as $page) {
                if ($page->getProject() == $project) {
                    $numBacklinks += $page->getBacklinks()->count();
                }
            }
        }

        return $numBacklinks;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Project
     */
    public function setName($name)
    {
        $this->name = mb_strtolower($name, 'UTF-8');

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return idn_to_ascii($this->name);
    }

    public function getNameForDisplay()
    {
        return idn_to_utf8($this->getName());
    }

    /**
     * Add subdomains
     *
     * @param \Pool\LinkmotorBundle\Entity\Domain $subdomains
     * @return Domain
     */
    public function addSubdomain(\Pool\LinkmotorBundle\Entity\Domain $subdomains)
    {
        $this->subdomains[] = $subdomains;
    
        return $this;
    }

    /**
     * Remove subdomains
     *
     * @param \Pool\LinkmotorBundle\Entity\Domain $subdomains
     */
    public function removeSubdomain(\Pool\LinkmotorBundle\Entity\Domain $subdomains)
    {
        $this->subdomains->removeElement($subdomains);
    }

    /**
     * Get subdomains
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getSubdomains()
    {
        return $this->subdomains;
    }

    /**
     * Set authority
     *
     * @param integer $authority
     * @return Domain
     */
    public function setAuthority($authority)
    {
        $this->authority = $authority;
    
        return $this;
    }

    /**
     * Get authority
     *
     * @return integer 
     */
    public function getAuthority()
    {
        return $this->authority;
    }

    /**
     * Set vendor
     *
     * @param \Pool\LinkmotorBundle\Entity\Vendor $vendor
     * @return Domain
     */
    public function setVendor(\Pool\LinkmotorBundle\Entity\Vendor $vendor = null)
    {
        $this->vendor = $vendor;
        $vendor->addDomain($this);

        return $this;
    }

    /**
     * Get vendor
     *
     * @return \Pool\LinkmotorBundle\Entity\Vendor
     */
    public function getVendor()
    {
        return $this->vendor;
    }

    /**
     * Set lastCrawlAt
     *
     * @param \DateTime $lastCrawlAt
     * @return Domain
     */
    public function setLastCrawlAt($lastCrawlAt)
    {
        $this->lastCrawlAt = $lastCrawlAt;
    
        return $this;
    }

    /**
     * @return bool
     */
    public function getNotYetCrawled()
    {
        return $this->lastCrawledAt === null;
    }

    /**
     * Get lastCrawlAt
     *
     * @return \DateTime 
     */
    public function getLastCrawlAt()
    {
        return $this->lastCrawlAt;
    }

    /**
     * Set lastCrawledAt
     *
     * @param \DateTime $lastCrawledAt
     * @return Domain
     */
    public function setLastCrawledAt($lastCrawledAt)
    {
        $this->lastCrawledAt = $lastCrawledAt;
    
        return $this;
    }

    /**
     * Get lastCrawledAt
     *
     * @return \DateTime 
     */
    public function getLastCrawledAt()
    {
        return $this->lastCrawledAt;
    }

    /**
     * Add blacklists
     *
     * @param \Pool\LinkmotorBundle\Entity\Blacklist $blacklists
     * @return Domain
     */
    public function addBlacklist(\Pool\LinkmotorBundle\Entity\Blacklist $blacklists)
    {
        $this->blacklists[] = $blacklists;
    
        return $this;
    }

    /**
     * Remove blacklists
     *
     * @param \Pool\LinkmotorBundle\Entity\Blacklist $blacklists
     */
    public function removeBlacklist(\Pool\LinkmotorBundle\Entity\Blacklist $blacklists)
    {
        $this->blacklists->removeElement($blacklists);
    }

    /**
     * Get blacklists
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getBlacklists()
    {
        return $this->blacklists;
    }

    /**
     * Add competitors
     *
     * @param \Pool\LinkmotorBundle\Entity\Competitor $competitors
     * @return Domain
     */
    public function addCompetitor(\Pool\LinkmotorBundle\Entity\Competitor $competitors)
    {
        $this->competitors[] = $competitors;
    
        return $this;
    }

    /**
     * Remove competitors
     *
     * @param \Pool\LinkmotorBundle\Entity\Competitor $competitors
     */
    public function removeCompetitor(\Pool\LinkmotorBundle\Entity\Competitor $competitors)
    {
        $this->competitors->removeElement($competitors);
    }

    /**
     * Get competitors
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCompetitors()
    {
        return $this->competitors;
    }

    /**
     * @param Project $project
     * @return bool
     */
    public function blacklistedIn(Project $project)
    {
        foreach ($this->getBlacklists() as $item) {

src/Pool/LinkmotorBundle/Controller/DomainController.php
<?php

namespace Pool\LinkmotorBundle\Controller;

use Pool\LinkmotorBundle\Entity\Domain;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Request;

class DomainController extends BaseController
{
    /**
     * @Route("/{_locale}/app/domains/", defaults={"_locale" = "en"}, name="pool_linkmotor_domains_index")
     * @Method("GET")
     * @Template()
     */
    public function indexAction(Request $request)
    {
        $project = $this->getSelectedProject();
        if (!$project) {
            // @todo Wenn nur ein Projekt vorhanden ist, dieses sofort auswählen
            // @todo Wenn Domain nur in ein Projekt benutzt wird, dieses sofort auswählen
            return $this->noProjectSelectedRedirect();
        }
        if ($this->isLimitedProject($project)) {
            return $this->redirect($this->generateUrl('pool_linkmotor_limits_reached'));
        }

        if ($this->hasFilterChanged($request)) {
            // Notwendig, da der Parameter sonst auch beim Paginieren angehängt wird
            return $this->redirect($this->generateUrl('pool_linkmotor_domains_index'));
        }

        $domains = $this->getDoctrine()
            ->getRepository('PoolLinkmotorBundle:Domain')
            ->getForProject($project, $this->getFilter());

        $paginator  = $this->get('knp_paginator');
        $domains = $paginator->paginate(
            $domains,
            $this->getRequest()->query->get('page', 1),
            $this->getItemsPerPage()
        );

        return array('project' => $project, 'domains' => $domains);
    }

    /**
     * @Route("/{_locale}/app/domains/view/{id}/", defaults={"_locale" = "en"}, name="pool_linkmotor_domains_view")
     * @Method("GET")
     * @Template()
     */
    public function viewAction(Domain $domain)
    {
        $project = $this->getSelectedProject();
        if (!$project) {
            // @todo Wenn nur ein Projekt vorhanden ist, dieses sofort auswählen
            // @todo Wenn Domain nur in ein Projekt benutzt wird, dieses sofort auswählen
            return $this->noProjectSelectedRedirect();
        }
        if ($this->isLimitedProject($project)) {
            return $this->redirect($this->generateUrl('pool_linkmotor_limits_reached'));
        }

        return array('domain' => $domain, 'project' => $project);
    }

    /**
     * @Template()
     */
    public function filterAction()
    {
        $project = $this->getSelectedProject();
        if (!$project) {
            // @todo Wenn nur ein Projekt vorhanden ist, dieses sofort auswählen
            // @todo Wenn Domain nur in ein Projekt benutzt wird, dieses sofort auswählen
            return $this->noProjectSelectedRedirect();
        }
        if ($this->isLimitedProject($project)) {
            return $this->redirect($this->generateUrl('pool_linkmotor_limits_reached'));
        }

        $vendors = $this->getDoctrine()->getRepository('PoolLinkmotorBundle:Vendor')->getForProject($project);

        return array(
            'vendors' => $vendors,
            'filter' => $this->getFilter()
        );
    }
}

src/Pool/LinkmotorBundle/Resources/views/Domain/filter.html.twig
<ul class="uk-subnav uk-subnav-pill filter">
    <li>
        <form class="uk-search autosubmit{% if filter['keyword'] %} used-filter{% endif %}" action="" method="get" data-uk-search>
            <input class="uk-search-field" name="changeKeywordFilter" type="search" placeholder="{% trans %}Search for URL or Email{% endtrans %}..." value="{{ filter['keyword'] }}">
            <button class="uk-search-close" type="reset"></button>
        </form>
    </li>
    {% if filter['keyword'] %}
        <li>
            <a class="uk-button uk-button-danger uk-button-small" href="?resetFilter">
                <i class="uk-icon-times-circle"></i> {% trans %}Reset{% endtrans %}
            </a>
        </li>
    {% endif %}
</ul>

src/Pool/LinkmotorBundle/Resources/views/Domain/index.html.twig
{% extends 'PoolLinkmotorBundle::layout.html.twig' %}

{% block title %}{% trans %}Domains{% endtrans %} - {% endblock %}

{% block content %}

    {% render controller('PoolLinkmotorBundle:Domain:filter') %}

    <table class="uk-table uk-table-striped uk-table-hover">
        <tr>
            <th>{% trans %}Name{% endtrans %}</th>
            <th>{% trans %}Pages{% endtrans %}</th>
            <th>{% trans %}Backlinks{% endtrans %}</th>
            <th><abbr title="{% trans %}Domain Authority - Data from Moz.com{% endtrans %}" data-uk-tooltip>DA</abbr></th>
            <th>{% trans %}Vendor{% endtrans %}</th>
        </tr>
        {% for domain in domains %}
            <tr>
                <td>
                    <i class="uk-icon-folder-close"></i>
                    <a href="{{ path('pool_linkmotor_domains_view', {id:domain.id}) }}">
                        <strong>{{ domain.nameForDisplay }}</strong>
                    </a>
                    {% if domain.blacklistedIn(project) %}
                        <div class="uk-badge">{% trans %}Blacklist{% endtrans %}</div>
                    {% endif %}
                    {% if domain.competitorIn(project) %}
                        <div class="uk-badge">{% trans %}Competitor{% endtrans %}</div>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('pool_linkmotor_pages_index', {type:'all'}) }}?resetFilter&changeDomainFilter={{ domain.id }}">
                        {{ domain.numPages(project) }}
                    </a>
                </td>
                <td>
                    <a href="{{ path('pool_linkmotor_backlinks_index', {type:'all'}) }}?resetFilter&changeDomainFilter={{ domain.id }}">
                        {{ domain.numBacklinks(project) }}
                    </a>
                </td>
                <td>{{ valueOrSpinner(domain.authority, 0) }}</td>
                <td>
                    {% if not domain.vendor %}
                        <a class="uk-text-muted" href="{{ path('pool_linkmotor_domains_set_vendor', {id:domain.id}) }}">
                            <i class="uk-icon-plus-square"></i> <small>{% trans %}add{% endtrans %}</small>
                        </a>
                    {% else %}
                        <a data-uk-tooltip title="{{ domain.vendor.displayName }} {{ domain.vendor.phone }}" href="{{ path('pool_linkmotor_vendors_view', {id:domain.vendor.id}) }}">
                            <i class="uk-icon-user"></i> <small>{% trans %}show{% endtrans %}</small>
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

    {{ knp_pagination_render(domains) }}
{% endblock %}

src/Pool/LinkmotorBundle/Resources/views/Domain/info.html.twig
<table class="uk-table uk-table-striped">
    <h3 class="uk-panel-title"><i class="uk-icon-info-circle"></i> Domain-Info</h3>
    <thead>
        <tr>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="uk-width-custom uk-text-bold" style="width: 150px;">{% trans %}Domain{% endtrans %}</td>
            <td>
                <a href="{{ path('pool_linkmotor_domains_view', {id:backlink.page.subdomain.domain.id}) }}">
                    {{ backlink.page.subdomain.domain.nameForDisplay }}
                </a>
            </td>
        </tr>
        <tr>
            <td class="uk-width-custom uk-text-bold" style="width: 150px;">{% trans %}Vendor{% endtrans %}</td>
            <td>
                {% if backlink.page.subdomain.vendor %}
                    <a class="uk-text-muted" href="{{ path('pool_linkmotor_vendors_view', {id:backlink.page.subdomain.vendor.id}) }}"
                       data-uk-tooltip="{pos:'bottom'}" title="Subdomain-{% trans %}Vendor{% endtrans %}">
                        {{ backlink.page.subdomain.vendor.displayName }}
                    </a>
                {% elseif backlink.page.subdomain.domain.vendor %}
                    <a href="{{ path('pool_linkmotor_vendors_view', {id:backlink.page.subdomain.domain.vendor.id}) }}">
                        {{ backlink.page.subdomain.domain.vendor.displayName }}
                    </a>
                {% else %}
                    <a class="uk-text-muted" href="{{ path('pool_linkmotor_domains_set_vendor', {id:backlink.page.subdomain.domain.id}) }}">
                        <i class="uk-icon-plus-square"></i> <small>{% trans %}add{% endtrans %}</small>
                    </a>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td class="uk-width-custom uk-text-bold" style="width: 150px;">{% trans %}Assigned to{% endtrans %}</td>
            <td>
                {{ backlink.assignedTo.displayName }}
            </td>
        </tr>
    </tbody>
</table>

src/Pool/LinkmotorBundle/Resources/views/Domain/view.html.twig
{% extends 'PoolLinkmotorBundle::layout.html.twig' %}

{% block title %}{{ domain.name }} - {% trans %}Domains{% endtrans %} - {% endblock %}

{% block content %}
    <h2>{% trans %}Overview{% endtrans %}</h2>
    <dl class="uk-description-list uk-description-list-horizontal">
        <dt>{% trans %}Name{% endtrans %}</dt>
        <dd>{{ domain.nameForDisplay }}</dd>

        <dt>{% trans %}Pages{% endtrans %}</dt>
        <dd>
            <a href="{{ path('pool_linkmotor_pages_index', {type:'all'}) }}?resetFilter&changeDomainFilter={{ domain.id }}">
                {{ domain.numPages(project)|localeNumber }}
            </a>
        </dd>

        <dt>{% trans %}Backlinks{% endtrans %}</dt>
        <dd>
            <a href="{{ path('pool_linkmotor_backlinks_index', {type:'all'}) }}?resetFilter&changeDomainFilter={{ domain.id }}">
                {{ domain.numBacklinks(project)|localeNumber }}
            </a>
        </dd>

        <dt><abbr title="{% trans %}Domain Authority - Data from Moz.com{% endtrans %}" data-uk-tooltip>DA</abbr></dt>
        <dd>{{ valueOrSpinner(domain.authority, 0) }}</dd>

        <dt>{% trans %}Vendor{% endtrans %}</dt>
        <dd>
            {% if not domain.vendor %}
                <a class="uk-button uk-button-mini" href="{{ path('pool_linkmotor_domains_set_vendor', {id:domain.id}) }}">
                    <i class="uk-icon-plus-square"></i> {% trans %}add{% endtrans %}
                </a>
            {% else %}
                <a href="{{ path('pool_linkmotor_vendors_view', {id:domain.vendor.id}) }}">
                    {{ domain.vendor.displayName }}
                </a>
            {% endif %}
        </dd>
    </dl>

    <h2>{% trans %}Backlinks{% endtrans %}</h2>
    <table class="uk-table uk-table-striped uk-table-hover">
        <tr>
            <th>{% trans %}Page{% endtrans %}</th>
            <th>{% trans %}Target-URL{% endtrans %}</th>
            <th>{% trans %}Anchor{% endtrans %}</th>
            <th>{% trans %}Type{% endtrans %}</th>
            <th>{% trans %}Follow{% endtrans %}</th>
        </tr>
        {% for subdomain in domain.subdomains %}
            {% for page in subdomain.pages %}
                {% if page.project == project %}
                    {% for backlink in page.backlinks %}
                        {% if backlink.project == project %}
                            <tr>
                                <td>
                                    <a href="{{ path('pool_linkmotor_backlinks_view', {id:backlink.id}) }}">
                                        {{ backlink.page.fullForDisplay }}
                                    </a>
                                </td>
                                <td>{{ backlink.url }}</td>
                                <td>{{ backlink.anchor }}</td>
                                <td>{{ backlink.typeName }}</td>
                                <td>{{ backlink.follow ? 'Yes'|trans : 'No'|trans }}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endfor %}
        {% endfor %}
    </table>

    {% include 'PoolLinkmotorBundle:Page:snippetList.html.twig' with {domain:domain} %}
    {% include 'PoolLinkmotorBundle:Subdomain:snippetList.html.twig' with {subdomains:domain.subdomains} %}

{% endblock %}