src/Pool/LinkmotorBundle/Entity/Import.php
<?php

namespace Pool\LinkmotorBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Import
 *
 * @ORM\Table(name="imports")
 * @ORM\Entity(repositoryClass="Pool\LinkmotorBundle\Entity\ImportRepository")
 */
class Import
{
    const TYPE_LINKBIRD = 1;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * var integer 1 = Linkbird
     *
     * @ORM\Column(name="type", type="integer");
     */
    protected $type;

    /**
     * @var string filename
     *
     * @ORM\Column(name="filename", type="string", length=128)
     */
    protected $filename;

    /**
     * @var string hash - is used to store the input- and output-files
     *
     * @ORM\Column(name="hash", type="string", length=32)
     */
    protected $hash;

    /**
     * @var integer
     *
     * @ORM\Column(name="step", type="integer");
     */
    protected $step;

    /**
     * @var array (stored as JSON) - holds additional information, like the result overview of the import
     *
     * @ORM\Column(name="data", type="text");
     */
    protected $data;

    /**
     * @var integer
     *
     * @ORM\Column(name="progress", type="integer");
     */
    protected $progress;

    /**
     * @ORM\Column(name="created_at", type="datetime")
     */
    protected $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="Project", inversedBy="imports")
     * @ORM\JoinColumn(name="project_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $project;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="imports")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    protected $createdBy;

    public function __construct()
    {
        $this->setStep(0);
        $this->setProgress(0);
        $this->setData(array());
        $this->setCreatedAt(new \DateTime());
    }

    public function getNumRowsImported()
    {
        $data = $this->getData();

        return isset($data['numRowsImported']) ? $data['numRowsImported'] : 0;
    }

    public function getDisplayStatus()
    {
        if ($this->step == 1) {
            return 'Analyzing import';
        } elseif ($this->step == 3) {
            return 'Waiting for data import';
        } elseif ($this->step == 4) {
            return 'Importing';
        } elseif ($this->step == 99) {
            $data = $this->getData();
            return $data['msg'];
        }

        return 'Waiting for analyze';
    }

    public function statusIsWaiting()
    {
        if ($this->step < 99 && $this->step != 2) {
            return true;
        }

        return false;
    }

    public function getImportFilename()
    {
        return $this->getHash() . '-' . $this->getProject()->getId();
    }

    public function getTranscriptFilename()
    {
        return $this->getHash() . '-' . $this->getProject()->getId() . '.transcript';
    }

    public function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    public function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads/imports';
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set type
     *
     * @param integer $type
     * @return Import
     */
    public function setType($type)
    {
        $this->type = $type;
    
        return $this;
    }

    /**
     * Get type
     *
     * @return integer 
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set hash
     *
     * @param string $hash
     * @return Import
     */
    public function setHash($hash)
    {
        $this->hash = $hash;
    
        return $this;
    }

    /**
     * Get hash
     *
     * @return string 
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Set step
     *
     * @param integer $step
     * @return Import
     */
    public function setStep($step)
    {
        $this->step = $step;
    
        return $this;
    }

    /**
     * Get step
     *
     * @return integer 
     */
    public function getStep()
    {
        return $this->step;
    }

    /**
     * Set data
     *
     * @param array $data
     * @return Import
     */
    public function setData($data)
    {
        if (!is_array($data)) {
            $data = array();
        }
        $this->data = @json_encode($data);

        return $this;
    }

    /**
     * Get data
     *
     * @return string 
     */
    public function getData()
    {
        $data = @json_decode($this->data, true);
        if (!is_array($data)) {
            $data = array();
        }
        return $data;
    }

    /**
     * Set progress
     *
     * @param integer $progress
     * @return Import
     */
    public function setProgress($progress)
    {
        $this->progress = $progress;
    
        return $this;
    }

    /**
     * Get progress
     *
     * @return integer 
     */
    public function getProgress()
    {
        return $this->progress;
    }

    /**
     * Set createdBy
     *
     * @param \Pool\LinkmotorBundle\Entity\User $createdBy
     * @return Import
     */
    public function setCreatedBy(User $createdBy = null)
    {
        $this->createdBy = $createdBy;
    
        return $this;
    }

    /**
     * Get createdBy
     *
     * @return \Pool\LinkmotorBundle\Entity\User
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * Set filename
     *
     * @param string $filename
     * @return Import
     */
    public function setFilename($filename)
    {
        $this->filename = $filename;
        $this->setHash(md5($filename . time()));

        return $this;
    }

    /**
     * Get filename
     *
     * @return string 
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Import
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set project
     *
     * @param \Pool\LinkmotorBundle\Entity\Project $project
     * @return Import
     */
    public function setProject(\Pool\LinkmotorBundle\Entity\Project $project = null)
    {
        $this->project = $project;
    
        return $this;
    }

    /**
     * Get project
     *
     * @return \Pool\LinkmotorBundle\Entity\Project
     */
    public function getProject()
    {
        return $this->project;
    }
}

src/Pool/LinkmotorBundle/Controller/ImportController.php
<?php

namespace Pool\LinkmotorBundle\Controller;

use Pool\LinkmotorBundle\Entity\Import;
use Pool\LinkmotorBundle\Form\Type\LinkbirdImportStep2Type;
use Pool\LinkmotorBundle\Form\Type\LinkbirdImportType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ImportController extends BaseController
{
    /**
     * @Route("/{_locale}/app/imports/", defaults={"_locale" = "en"},
     *        name="pool_linkmotor_imports_index")
     * @Method("GET")
     * @Template()
     */
    public function indexAction(Request $request)
    {
        $project = $this->getSelectedProject();
        if (!$project) {
            // @todo Wenn nur ein Projekt vorhanden ist, dieses sofort auswählen
            return $this->noProjectSelectedRedirect();
        }
        if ($this->isLimitedProject($project)) {
            return $this->redirect($this->generateUrl('pool_linkmotor_limits_reached'));
        }

        $imports = $this->getDoctrine()
            ->getRepository('PoolLinkmotorBundle:Import')
            ->findByProject($project);

        return array('imports' => $imports);
    }

    /**
     * @Route("/{_locale}/app/imports/add/", defaults={"_locale" = "en"},
     *        name="pool_linkmotor_imports_add")
     * @Method({"GET", "POST"})
     * @Template()
     */
    public function addAction(Request $request)
    {
        $project = $this->getSelectedProject();
        if (!$project) {
            // @todo Wenn nur ein Projekt vorhanden ist, dieses sofort auswählen
            return $this->noProjectSelectedRedirect();
        }
        if ($this->isLimitedProject($project)) {
            return $this->redirect($this->generateUrl('pool_linkmotor_limits_reached'));
        }

        $form = $this->createForm(new LinkbirdImportType());

        if ($request->getMethod() == 'POST') {
            $form->submit($request);
            $uploadedFile = $form['file']->getData();
            $isValid = true;
            if ($uploadedFile == null) {
                $isValid = false;
                $errorMessage = $this->get('translator')
                    ->trans('You need to specify a file to upload', array(), 'validators');
                $form->addError(new FormError($errorMessage));
            }
            if ($isValid) {
                $import = new Import();
                $import->setType(Import::TYPE_LINKBIRD);
                $import->setProject($project);
                $import->setCreatedBy($this->getUser());
                $import->setFilename($uploadedFile->getClientOriginalName());

                $uploadedFile->move($import->getUploadRootDir(), $import->getImportFilename());

                $em = $this->getDoctrine()->getManager();
                $em->persist($import);
                $em->flush();

                $this->get('session')->getFlashBag()->add(
                    'success',
                    'The import has been started'
                );

                return $this->redirect($this->generateUrl('pool_linkmotor_imports_index'));
            }
        }

        return array('form' => $form->createView());
    }

    /**
     * @Route("/{_locale}/app/imports/{id}/step-2/", defaults={"_locale" = "en"},
     *        name="pool_linkmotor_backlinks_import_step2")
     * @Method({"GET", "POST"})
     * @Template()
     */
    public function step2Action(Request $request, Import $import)
    {
        $project = $this->getSelectedProject();
        if (!$project || $project != $import->getProject()) {
            $project = $import->getProject();
            $this->setSelectedProject($project);
        }
        if ($this->isLimitedProject($project)) {
            return $this->redirect($this->generateUrl('pool_linkmotor_limits_reached'));
        }

        $linkbirdAnalyzeData = $import->getData();

        $linkbirdImportStep2Type = new LinkbirdImportStep2Type(
            $linkbirdAnalyzeData['users'],
            $linkbirdAnalyzeData['projects']
        );
        $form = $this->createForm($linkbirdImportStep2Type);

        if ($request->getMethod() == 'POST') {
            $form->submit($request);
            $linkbirdProject = $form['project']->getData();
            $userMappingEmpty = $form['userMappingEmpty']->getData()->getId();
            $userMapping = array();
            foreach ($linkbirdAnalyzeData['users'] as $idx => $user) {
                $userMapping[$idx] = $form['userMapping' . $idx]->getData()->getId();
            }

            $data = $import->getData();
            $data['project'] = $linkbirdAnalyzeData['projects'][$linkbirdProject];
            $data['userMappingEmpty'] = $userMappingEmpty;
            $data['userMapping'] = $userMapping;
            $import->setData($data);
            $import->setStep(3);
            $em = $this->getDoctrine()->getManager();
            $em->persist($import);
            $em->flush();

            $this->get('session')->getFlashBag()->add(
                'success',
                'The import will continue shortly'
            );

            return $this->redirect($this->generateUrl('pool_linkmotor_imports_index'));
        }

        return array('form' => $form->createView(), 'import' => $import);
    }

    /**
     * @todo Dafür sorgen, dass die Dateien auch gelöscht werden, wenn
     * @todo die Entity durch das Löschen des Projektes entfernt wird
     * @Route("/{_locale}/app/imports/{id}/delete/", defaults={"_locale" = "en"},
     *        name="pool_linkmotor_backlinks_import_delete")
     * @Method({"GET", "POST"})
     * @Template()
     */
    public function deleteAction(Request $request, Import $import)
    {
        $project = $this->getSelectedProject();
        if (!$project || $project != $import->getProject()) {
            $project = $import->getProject();
            $this->setSelectedProject($project);
        }
        if ($this->isLimitedProject($project)) {
            return $this->redirect($this->generateUrl('pool_linkmotor_limits_reached'));
        }

        if ($request->getMethod() == 'POST') {
            $uploadRootDir = $import->getUploadRootDir();
            @unlink($uploadRootDir . '/' . $import->getImportFilename());
            @unlink($uploadRootDir . '/' . $import->getTranscriptFilename());

            $em = $this->getDoctrine()->getManager();
            $em->remove($import);
            $em->flush();

            $this->get('session')->getFlashBag()->add(
                'success',
                'The import has been deleted'
            );

            return $this->redirect($this->generateUrl('pool_linkmotor_imports_index'));
        }

        return array('import' => $import);
    }

    /**
     * @Route("/{_locale}/app/imports/{id}/download-transcript/", defaults={"_locale" = "en"},
     *        name="pool_linkmotor_backlinks_import_download_transcript")
     * @Method("GET")
     */
    public function downloadTranscriptAction(Import $import)
    {
        $project = $this->getSelectedProject();
        if (!$project || $project != $import->getProject()) {
            $project = $import->getProject();
            $this->setSelectedProject($project);
        }
        if ($this->isLimitedProject($project)) {
            return $this->redirect($this->generateUrl('pool_linkmotor_limits_reached'));
        }

        $response = new Response();

        $uploadRootDir = $import->getUploadRootDir();
        $response->setContent(@file_get_contents($uploadRootDir . '/' . $import->getTranscriptFilename()));

        $response->headers->set('Content-Type', 'text/csv');
        $response->headers->set('Content-Disposition', 'attachment; filename="transcript.csv"');

        return $response;
    }

    /**
     * @Route("/{_locale}/app/imports/{id}/ajax-refresh/", defaults={"_locale" = "en"},
     *        name="pool_linkmotor_backlinks_import_ajax_refresh")
     * @Method("GET")
     * @Template()
     */
    public function ajaxRefreshAction(Import $import)
    {
        return array('import' => $import);
    }
}

src/Pool/LinkmotorBundle/Resources/views/Import/add.html.twig
{% extends 'PoolLinkmotorBundle::layout.html.twig' %}

{% block title %}{% trans %}Linkbird{% endtrans %} - {% trans %}Import{% endtrans %} - {% trans %}Backlinks{% endtrans %} - {% endblock %}

{% block subnav %}
    {% include 'PoolLinkmotorBundle:Import:subnav.html.twig' %}
{% endblock %}

{% block content %}
    <h2>{% trans %}Add new Linkbird-Import{% endtrans %}</h2>
        <p>
            {% trans %}This is where you can import your .XLSX-File from Linkbird.{% endtrans %}
        </p>

    <form class="uk-form uk-form-horizontal" action="{{ path('pool_linkmotor_imports_add') }}" method="post" {{ form_enctype(form) }}>
        {{ form_errors(form) }}

        <fieldset class="filter">
            {{ form_rest(form) }}
        </fieldset>

        <input class="uk-button uk-button-primary" type="submit" value="{% trans %}Upload{% endtrans %}" />
        <a class="uk-button-small uk-button-link lmcancelbutton" href="{{ path('pool_linkmotor_imports_index') }}">{% trans %}Cancel{% endtrans %}</a>
    </form>
{% endblock %}

src/Pool/LinkmotorBundle/Resources/views/Import/ajaxRefresh.html.twig
{% include 'PoolLinkmotorBundle:Import:row.html.twig' %}

src/Pool/LinkmotorBundle/Resources/views/Import/delete.html.twig
{% extends 'PoolLinkmotorBundle::layout.html.twig' %}

{% block title %}{% trans %}Linkbird{% endtrans %} - {% trans %}Import{% endtrans %} - {% trans %}Backlinks{% endtrans %} - {% endblock %}

{% block subnav %}
    {% include 'PoolLinkmotorBundle:Import:subnav.html.twig' %}
{% endblock %}

{% block content %}
    <h2>{% trans %}Delete import{% endtrans %}</h2>

    <form class="uk-form uk-form-horizontal" action="{{ path('pool_linkmotor_backlinks_import_delete', {id:import.id}) }}" method="post">
        <fieldset class="uk-alert-danger uk-alert-large">
            <h2>{% trans %}Are you sure?{% endtrans %}</h2>
            <p>{% trans %}Deleting this import cannot be undone!{% endtrans %}</p>
            <p class="uk-text-bold">{% trans %}The imported backlinks will, of course, not be removed from this project!{% endtrans %}</p>
        </fieldset>
        <input class="uk-button uk-button-danger" type="submit" value="{% trans %}Delete{% endtrans %}" />
        <a class="uk-button" href="{{ path('pool_linkmotor_imports_index') }}">{% trans %}Cancel{% endtrans %}</a>
    </form>

{% endblock %}

src/Pool/LinkmotorBundle/Resources/views/Import/index.html.twig
{% extends 'PoolLinkmotorBundle::layout.html.twig' %}

{% block title %}{% trans %}Linkbird{% endtrans %} - {% trans %}Import{% endtrans %} - {% trans %}Backlinks{% endtrans %} - {% endblock %}

{% block subnav %}
    {% include 'PoolLinkmotorBundle:Import:subnav.html.twig' %}
{% endblock %}

{% block content %}
    <h2>{% trans %}Import backlinks from Linkbird{% endtrans %}</h2>
        <a class="uk-button uk-button-primary" href="{{ path('pool_linkmotor_imports_add') }}">
        <i class="uk-icon-plus"></i> {% trans %}Add new Linkbird-Import{% endtrans %}
    </a>
    <table class="uk-table uk-table-striped uk-table-hover">
        <tr>
            <th>{% trans %}Filename{% endtrans %}</th>
            <th>{% trans %}Imported at{% endtrans %}</th>
            <th>{% trans %}Uploaded by{% endtrans %}</th>
            <th>{% trans %}Status{% endtrans %}</th>
            <th></th>
        </tr>
        {% for import in imports %}
            {% include 'PoolLinkmotorBundle:Import:row.html.twig' %}
        {% else %}
            <tr><td colspan="5"><em>{% trans %}No imports available{% endtrans %}</em></td></tr>
        {% endfor %}
    </table>
{% endblock %}

src/Pool/LinkmotorBundle/Resources/views/Import/row.html.twig
<tr{% if import.step not in [2, 5] and import.statusIsWaiting %} class="refresh-import" lm-data="{{ import.id }}"{% endif %}>
    <td>{{ import.filename }}</td>
    <td>{{ import.createdAt|date('d.m.Y') }}</td>
    <td>{{ import.createdBy.displayName }}</td>
    <td>
        {% if import.step == 2 %}
            <a class="uk-button uk-button-small uk-button-primary" href="{{ path('pool_linkmotor_backlinks_import_step2', {id:import.id}) }}">
                {% trans %}Ready for step 2{% endtrans %} &raquo;
            </a>
        {% elseif import.step == 5 %}
            {% trans with {'%num':import.numRowsImported} %}%num rows imported{% endtrans %}
        {% else %}
            {% if import.statusIsWaiting %}
                <i class="uk-icon-spinner uk-icon-spin"></i>
            {% endif %}
            <span{% if import.step == 99 %} class="uk-badge uk-badge-danger"{% endif %}>
                {{ import.displayStatus|trans }}
            </span>
            {% if import.progress > 0 %}
                <div class="uk-progress">
                    <div class="uk-progress-bar" style="width: {{ import.progress }}%;">
                        {{ import.progress }}%
                    </div>
                </div>
            {% endif %}
        {% endif %}
    </td>
    <td>
        {% if import.step == 5 %}
            <a class="uk-button uk-button-small" href="{{ path('pool_linkmotor_backlinks_import_download_transcript', {id:import.id}) }}">
                <i class="uk-icon-download"></i> {% trans %}Transcript{% endtrans %}
            </a>
        {% endif %}
        {% if import.step in [2, 5, 99] %}
            <a class="uk-button uk-button-small" href="{{ path('pool_linkmotor_backlinks_import_delete', {id:import.id}) }}">
                <i class="uk-icon-trash-o"></i> {% trans %}Delete{% endtrans %}
            </a>
        {% endif %}
    </td>
</tr>

src/Pool/LinkmotorBundle/Resources/views/Import/step2.html.twig
{% extends 'PoolLinkmotorBundle::layout.html.twig' %}

{% block title %}{% trans %}Linkbird{% endtrans %} - {% trans %}Import{% endtrans %} - {% trans %}Backlinks{% endtrans %} - {% endblock %}

{% block subnav %}
    {% include 'PoolLinkmotorBundle:Import:subnav.html.twig' %}
{% endblock %}

{% block content %}
    <h2>{% trans %}Import backlinks from Linkbird{% endtrans %}</h2>
    <div class="uk-alert">
        <p>
            <i class="uk-icon-info-sign"></i>
            {% trans %}help.import.linkbird.step2{% endtrans %}
        </p>
    </div>

    <form class="uk-form uk-form-horizontal" action="{{ path('pool_linkmotor_backlinks_import_step2', {id:import.id}) }}" method="post" {{ form_enctype(form) }}>
        {{ form_errors(form) }}

        <fieldset>
            <legend>{% trans %}Which project should be imported?{% endtrans %}</legend>
            {{ form_row(form.project) }}
        </fieldset>

        <fieldset>
            <legend>{% trans %}User mapping{% endtrans %}</legend>
            {{ form_rest(form) }}
        </fieldset>

        <input class="uk-button uk-button-primary" type="submit" value="{% trans %}Continue{% endtrans %} &raquo;" />
        <a class="uk-button" href="{{ path('pool_linkmotor_imports_index') }}">{% trans %}Cancel{% endtrans %}</a>
    </form>

    {% if log is defined %}
        <h2>{% trans %}Import report{% endtrans %}</h2>
        <div class="uk-alert">
            <p><i class="uk-icon-info-sign"></i> {% trans %}help.backlink.import.crawlnotice{% endtrans %}</p>
        </div>
        <table class="uk-table uk-table-condensed">
            <tr>
                <th>{% trans %}URL{% endtrans %}</th>
                <th>Target-URL</th>
                <th>{% trans %}Anchor{% endtrans %}</th>
                <th>{% trans %}Type{% endtrans %}</th>
                <th>Follow</th>
                <th>{% trans %}User{% endtrans %}</th>
                <th>{% trans %}Status{% endtrans %}</th>
            </tr>
            {% for invalidRow in invalidRows %}
                <tr>
                    <td>{{ invalidRow[0] }}</td>
                    <td>{{ invalidRow[1] }}</td>
                    <td>{{ invalidRow[2] }}</td>
                    <td>{{ invalidRow[3] }}</td>
                    <td>{{ invalidRow[4] }}</td>
                    <td>{{ invalidRow[5] }}</td>
                    <td>
                        <div class="uk-badge uk-badge-danger">
                            {% trans %}Wrong encoding{% endtrans %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
            {% for item in log %}
                <tr>
                    <td>{{ item.0 }}</td>
                    <td>{{ item.1 }}</td>
                    <td>{{ item.2 }}</td>
                    <td>{{ item.3 }}</td>
                    <td>{{ item.4 }}</td>
                    <td>
                        {% if item.5.displayName is defined %}
                            {{ item.5.displayName }}
                        {% else %}
                            {{ item.5 }}
                        {% endif %}
                    </td>
                    <td>
                        {% if item.6 == true%}
                            <div class="uk-badge uk-badge-success">OK</div>
                        {% else %}
                            <div class="uk-badge uk-badge-danger">{{ item.7|trans }}</div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}

{% endblock %}

src/Pool/LinkmotorBundle/Resources/views/Import/subnav.html.twig
<ul class="uk-tab">
    <li>
        <a href="{{ path('pool_linkmotor_backlinks_import') }}">
            {% trans %}CSV-Import{% endtrans %}
        </a>
    </li>
    <li class="uk-active">
        <a href="{{ path('pool_linkmotor_imports_index') }}">
            {% trans %}Linkbird Import{% endtrans %}
        </a>
    </li>
</ul>